### PR TITLE
Add ScreenDeleteAccount - Fix VPN-2778

### LINKED ISSUE #4401: Navigation bar displayed on delete account flow on iOS
**Affected versions:**

* 2.10.0 (2.202208302204);

**Tested Platforms:**

* iOS 14.7.1

**Prerequisites:**

* Have Mozilla VPN app installed and opened;

* Have a FxA account with an active subscription for Mozilla VPN;

* Be signed in;

**Steps to reproduce:**

1. Navigate to Settings - Profile screen;
1. Press the “Delete account” button;
1. Observe the screen;
1. Enter the password for the account and press the “Continue” button;
1. Observe the screen;

**Expected result:**

* For step 3 and 5: There is no navigation bar displayed on the screen;

**Actual result:**

* For step 3 and 5: The navigation bar is displayed on the screen;

**Notes:**

* See the attached video;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2778)
┆author: Bianca Hidecuti

### PR DESCRIPTION
**Pull request by lesleyjanenorton**
## Description

This adds VPNNavigator.ScreenDeleteAccount to fix #4401 / VPN-2778

## Reference

#4401 / VPN-2778

## Checklist
    
- [ ] My code follows the style guidelines for this project
- [ ] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [ ] I have performed a self review of my own code
- [ ] I have commented my code PARTICULARLY in hard to understand areas
- [ ] I have added thorough tests where needed

### CODE REVIEW

File: src/frontend/navigator.cpp [hunk 1]
```diff
@@ -126,6 +126,13 @@ ScreenData s_screens[] = {
         QVector<MozillaVPN::State>{MozillaVPN::StateMain},
         [](Navigator::Screen*) -> int8_t { return 0; },
         []() -> bool { return false; }),
+    ScreenData(
+        Navigator::Screen::ScreenDeleteAccount,
+        Navigator::LoadPolicy::LoadTemporarily,
+        "qrc:/ui/screens/ScreenDeleteAccount.qml",
+        QVector<MozillaVPN::State>{MozillaVPN::StateMain},
+        [](Navigator::Screen*) -> int8_t { return 0; },
```
Comment (bakulf) [inline src/frontend/navigator.cpp:134]: Can you write here something similar to screenUpdateRecommended?

File: src/frontend/navigator.cpp [hunk 2]
```diff
@@ -126,6 +126,13 @@ ScreenData s_screens[] = {
...
+        []() -> bool { return false; }),
```
Comment (bakulf) [inline src/frontend/navigator.cpp:135]: Maybe we can abort the account deletion op?

**Review by bakulf — APPROVED** [review]
