### PR TITLE
Incremental updates to in-app Sign in 

### LINKED ISSUE #2772: No display name/email in app authentication password screen
*VPN version:*

* 2.7.1 (16449500) - QT6 build;

*Platforms:*

* Android 10;

*Prerequisites:*

* Have an FxA account with a subscription for Mozilla VPN;
* Have a fresh install of the VPN QT6 build;

*Steps to reproduce:*

* Open the VPN app;
* Tap Sign up;
* Enter a valid, with subscription email;
* Observe password screen;

*Expected results:*

* A display name and email are displayed under account icon;

*Actual results:*

* No display name and email are displayed under account icon;

*Notes:*

* This is qa-major issue because the user cannot see what email address he used.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1755)

### LINKED ISSUE #2778: “Forgot your password?” link from Authentication screen not working
*Affected versions:*

* Mozilla VPN 2.7.1 (16449500)- QT6 build;

*Tested Platforms:*

* Android;

*Prerequisites:*

* Have a FxA account with or without an active subscription for Mozilla VPN;

* Have Mozilla VPN app installed and opened;

 *Steps to reproduce:*

* Tap on the “Sign up” / “Already a subscriber?” button;
* Enter your email address that is associated with the FxA account from prerequisites;
* Tap on the “Continue” button;
* Tap on the “Forgot your password?” link;
* Observe the behavior;

*Expected result:*

* User is redirected to the “Reset password” screen (?);

*Actual result:*

* Nothing happens. 

*Notes:*

* This is a qa-major issue because the user is not able to reset his password from client;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1761)

### PR DESCRIPTION
**Pull request by lesleyjanenorton**
- Fixes #2772
- Fixes #2778 
- Adds final content
- Adds 'invalid password' error messaging
- Adds TOS links and blurb (TODO should be component since it's copy/paste from in-app subscription view)

### CODE REVIEW

File: src/authenticationinapp/authenticationinapp.cpp [hunk 1]
```diff
@@ -90,7 +90,7 @@ void AuthenticationInApp::signIn() {
   m_listener->signIn();
 }
 
-const QString& AuthenticationInApp::emailAddress() const {
```
Comment (bakulf) [inline src/authenticationinapp/authenticationinapp.cpp:93]: I discussed this with Florian in another PR. Let's have it as a property.

**Review by bakulf — APPROVED** [review]
The emailAddress can be done as follow up.

**Review by flodolo — CHANGES_REQUESTED** [review]

File: translations/strings.yaml [hunk 2]
```diff
@@ -444,3 +444,12 @@ mobileOnboarding:
 
 inAppAuth:
   changeEmailLink: Change email
+  signInButton: Sign in
+  signInSubtitle: Continue to Mozilla VPN by signing in with your Firefox Account
```
[the remark this answers is not in the document]
Comment (lesleyjanenorton) [reply translations/strings.yaml:448]: thank you!

[the remark this answers is not in the document]
Comment (lesleyjanenorton) [reply translations/strings.yaml]: done

File: translations/strings.yaml [hunk 3]
```diff
@@ -444,3 +444,12 @@ mobileOnboarding:
...
 inAppAuth:
   changeEmailLink: Change email
+  signInButton: Sign in
+  signInSubtitle: Continue to Mozilla VPN by signing in with your Firefox account
+  forgotPasswordLink: Forgot your password?
+  passwordInputPlaceholder: Enter password
+  passwordInputLabel: Password
+  invalidPasswordErrorMessage: Invalid password. Please try again
+  signInDisclaimer:
+    value: By proceeding, you agree to the following
```
Comment (flodolo) [inline translations/strings.yaml:454]: Looks like GitHub ate my other comment when submitting the review :-( 

Do you have a screenshot of this looks like? I expect it to be problematic for several languages, because it's basically [forcing the order](https://mozilla-l10n.github.io/documentation/localization/dev_best_practices.html#avoid-concatenations-use-placeholders-instead), and we might need something else.

Comment (lesleyjanenorton) [reply translations/strings.yaml]: I removed the string and associated UI so that we can explore this and address in a follow-up PR. 

Screenshot of view from spec:
Screen Shot 2022-02-16 at 6 09 28 PM

Comment (flodolo) [reply translations/strings.yaml]: Unfortunately this design really doesn't work for localization :-(

**Review by flodolo — APPROVED** [review]

File: translations/strings.yaml (hunk 3 above)
Comment (lesleyjanenorton) [reply translations/strings.yaml]: Noted. Thank you for flagging! I filed [this ticket](https://mozilla-hub.atlassian.net/browse/VPN-1774) to address this. cc @peterbenvenuto @chrisrooneys
