### PR TITLE
Language

### LINKED ISSUE #754: VPN Languages are not alphabetically ordered
**Affected versions:**
- v. 2.1.0;

**Affected platforms**
- Windows 10

**Prerequisites:**
- Have the VPN app installed;
- Have a FxA account with active subscription for Mozilla VPN;

**Steps to reproduce**
1. Open the VPN 
2. Go to Settings -> Language.
3. Check how the available languages are displayed.

**Expected results**
- The languages are alphabetically ordered.

**Actual Results**
- The available languages are randomly displayed.

Screenshot_21

### PR DESCRIPTION
**Pull request by bakulf**
- Closes #754
- better english language names

### CODE REVIEW

File: src/localizer.cpp [hunk 1]
```diff
@@ -185,15 +195,29 @@ QVariant Localizer::data(const QModelIndex& index, int role) const {
...
+  for (const Language& language : m_languages) {
+    languages.append(language.m_code);
+  }
+
+  return languages;
+}
+
+bool Localizer::languageSort(const Localizer::Language& a,
+                             const Localizer::Language& b) {
+  return a.m_localizedName < b.m_localizedName;
```
Comment (bakulf) [inline src/localizer.cpp:222]: I would like to use QCollator but it doesn't work on Linux as it should.
If this doesn't work, I can investigate why we have a crash when using QCollator

File: src/localizer.cpp [hunk 2]
```diff
@@ -29,7 +29,10 @@ QMap<QString, StaticLanguage> s_languageMap{
     {"co", StaticLanguage{"Corsu", ""}},
     {"es_AR", StaticLanguage{"Spanish (Argentina)", "Español, Argentina"}},
     {"es_MX", StaticLanguage{"Spanish (Mexico)", "Español, México"}},
+    {"en_GB", StaticLanguage{"English (United Kingdom)", ""}},
```
Comment (flodolo) [inline src/localizer.cpp:32]: Maybe just UK, to avoid the language getting too long?

**Review by flodolo — APPROVED** [review]

File: src/localizer.cpp (hunk 2 above)
Comment (bakulf) [reply src/localizer.cpp:32]: We have space enough because the language is in a separate line.
image
