### PR TITLE
Auth flow updates

### LINKED ISSUE #2870: Credentials fields` validation is done to early
**VPN version:**

* 2.7.1 (16460300) - QT6 build;

**Platforms:**

* Android 9;

**Prerequisites:**

* Have an account with a subscription for Mozilla VPN;

* Have the Mozilla VPN app installed;

**Steps to reproduce:**

1. Open the Mozilla VPN app
1. Tap on the email address test field to start the login process;

**Expected results:**

* There user is able to insert their email address and the validation is done once the user taps “Done” on the keyboard or “Continue” on the app screen;

**Actual results:**

* The validation is done instantly at tap within the filed and the field turns RED; 

**Note:** please see below image

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1835)

### PR DESCRIPTION
**Pull request by lesleyjanenorton**
This PR:
- Adds VPNInAppAuthenticationInputs.qml to consolidate duped code across all auth templates (except password creation)
- Adds VPNInAppAuthenticationErrorPopup.qml to surface authentication errors not relevant to a specific input. 

Also:
  - Valid forms can be submitted by hitting 'Enter'
  - Adds `inputMethodHints` to email entry text field to cue mobile devices and improve native keyboard options on Apple
  - Email validation occurs after hitting "submit"
  - Handles all auth errors currently exposed to the QML
  
To follow: 
- final content
- final TOS content/UI
- tests
- password creation fixes
- more error handling, form polish, etc.

Fixes #2870 , #2823 , #2818, #2817, VPN-1771, VPN-1610, VPN-1611

<table>
<tr>
<td>
Screen Shot 2022-03-03 at 10 46 25 AM
</td>
<td>
Screen Shot 2022-03-03 at 10 46 32 AM

</td>
</tr>
<tr>
<td>
Screen Shot 2022-03-03 at 11 30 03 AM

</td>
<td>
Screen Shot 2022-03-03 at 10 46 13 AM
</td>
</tr>
<tr>
<td>
Screen Shot 2022-03-03 at 11 30 19 AM
</td>
<td>
Screen Shot 2022-03-03 at 11 31 51 AM

</td>
</tr>

<tr>
<td>
Screen Shot 2022-03-03 at 10 50 38 AM
</td>
<td>
Screen Shot 2022-03-03 at 10 54 51 AM

</td>
</tr>
<tr>
<td>
Screen Shot 2022-03-03 at 10 47 59 AM
</td>

</tr>

</table>

### CODE REVIEW

File: src/authenticationinapp/authenticationinapplistener.cpp [hunk 1]
```diff
@@ -557,7 +557,6 @@ void AuthenticationInAppListener::processErrorCode(int errorCode) {
       break;
 
     case 127:  // Invalid unblock code
-      aip->requestState(AuthenticationInApp::StateStart, this);
```
Comment (bakulf) [inline src/authenticationinapp/authenticationinapplistener.cpp:560]: Why this? At this point we are in some verification state. If not `start`, at least we need to be in a `unblock code needed`

**Review by bakulf — APPROVED** [review]
