### PR TITLE
Fix random timout banner

### LINKED ISSUE #495: “No internet connection. Try again!” red banner appears after a few seconds from turning on the VPN
#### Affected versions:
- 2.0.3 beta-debug build; 

#### Affected Platforms:
- All Android;

#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open the VPN app;
2. Tap to turn ON the VPN;
3. Wait about 10-15 seconds;

#### Expected result:
- Nothing strange happens.

#### Actual result:
- The “No internet connection. Try again!” red banner is displayed.

#### Notes:
- while the banner is being displayed, the VPN is still ON.

https://user-images.githubusercontent.com/15685960/105497416-79676a80-5cc7-11eb-9b3c-d294d65452cd.mp4

### PR DESCRIPTION
**Pull request by strseb**
Closes #495 

Issue here is: 
We have a task that starts an http-request.  (e.g. account&Servers)
We connect vpn.
The Request times out, as expected.  
We show the no connection banner.

My idea: Add a new connection-error for things that might be caused by vpn and are okay to ignore if the vpn is connected.

### CODE REVIEW

File: src/errorhandler.cpp [hunk 1]
```diff
@@ -38,7 +38,7 @@ ErrorHandler::ErrorType ErrorHandler::toErrorType(
     case QNetworkReply::HostNotFoundError:
       [[fallthrough]];
     case QNetworkReply::TimeoutError:
```
Comment (bakulf) [inline src/errorhandler.cpp:40]: This is wrong. Host-Not-Found should not be treated at "VPNDepedentConnectionError' right?

**Review by bakulf — CHANGES_REQUESTED** [review]

File: src/errorhandler.cpp (hunk 1 above)
Comment (strseb) [reply src/errorhandler.cpp:40]: Right, that was not supposed to be changed.
