### PR TITLE
Wait for the Correct IP to be fetched

### LINKED ISSUE #549: "Connection Information" screen lists real IP
#### Affected versions:
- v. 2.0.3 last build; 

#### Affected Platforms:
- Windows 10;
- Android 10;

#### Prerequisites:
-  Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open VPN app;
2. Turn ON the VPN;
3. Select a random region;
4. Go to Connection Information screen and observe the IP;

#### Expected result:
- The IP of the selected region is listed;

#### Actual result:
- The real IP is displayed;

#### Notes:
- ipinfo.ro lists the correct IP (the one of the selected region)

**- Android** 
-- selected region IP is displayed after 20-30 seconds from location switch;
-- turning off-on the VPN, without changing the location, also triggers a different IP (maybe this is expected);

### PR DESCRIPTION
**Pull request by strseb**
Prevent to fetch the ip if we're not connected so the real ip is not shown while we try to get the vpn-ed ip. 
Assert that the fetched ip has to be reported in the same country as we are connected to, otherwise retry. 
Oh and change the "unknown" string to "loading".. as we're probably loading when the user sees this. :) 

Closes #549

### CODE REVIEW

File: src/connectiondataholder.cpp [hunk 1]
```diff
@@ -224,14 +232,23 @@ void ConnectionDataHolder::updateIpAddress() {
...
             QJsonDocument json = QJsonDocument::fromJson(data);
             if (json.isObject()) {
               QJsonObject obj = json.object();
 
+              QJsonValue country = obj.take("country");
+              if (country.toString().toLower() !=
+                  MozillaVPN::instance()->currentServer()->countryCode()) {
+                logger.log() << "Reported ip not in the right country, retry!";
+                m_updatingIpAddress = false;
+                updateIpAddress();
```
Comment (bakulf) [inline src/connectiondataholder.cpp:244]: if for any reason the server goes out of sync, this method generates a loop of updateIpAddress(). Do we care about checking the countryCode ?

**Review by bakulf — CHANGES_REQUESTED** [review]
All good! Just a question about the loop.

File: src/connectiondataholder.cpp (hunk 1 above)
Comment (strseb) [reply src/connectiondataholder.cpp:244]: Sadly thats essential. Even after confirming we might encounter a stray request that did not yet use the vpn, for whatever reason. I would rather add an exit condition then removing this :)

Comment (bakulf) [reply src/connectiondataholder.cpp:244]: We spoke about this on slack. This code has to changed. Maybe a simple timer can help.

File: src/connectiondataholder.cpp [hunk 2]
```diff
@@ -224,14 +233,29 @@ void ConnectionDataHolder::updateIpAddress() {
   connect(request, &NetworkRequest::requestCompleted,
           [this](QNetworkReply*, const QByteArray& data) {
             logger.log() << "IP address request completed";
-
             QJsonDocument json = QJsonDocument::fromJson(data);
             if (json.isObject()) {
               QJsonObject obj = json.object();
 
+              QJsonValue country = obj.take("country");
+              if (!m_retryIssued &&
```
Comment (bakulf) [inline src/connectiondataholder.cpp:241]: you need to reset m_retryIssued. Or maybe you can simply get rid of this variable in this way:
```
if (m_checkStatusTimer.isActive() && country.toString().toLower() !=
                      MozillaVPN::instance()->currentServer()->countryCode()) {
```

File: src/connectiondataholder.cpp [hunk 3]
```diff
@@ -224,14 +233,29 @@ void ConnectionDataHolder::updateIpAddress() {
...
+                  country.toString().toLower() !=
+                      MozillaVPN::instance()->currentServer()->countryCode()) {
+                // In case the country-we're reported in does not match the
+                // connected server we may retry only once.
+                logger.log() << "Reported ip not in the right country, retry!";
+                TimerSingleShot::create(this, 3000, [this]() {
+                  m_updatingIpAddress = false;
+                  updateIpAddress();
+                });
+                m_retryIssued = true;
```
Comment (bakulf) [inline src/connectiondataholder.cpp:251]: What about if we show the IP even if it's the wrong one? We will update it in a few seconds...

**Review by bakulf — CHANGES_REQUESTED** [review]

File: src/connectiondataholder.cpp (hunk 3 above)
Comment (strseb) [reply src/connectiondataholder.cpp:251]: good point

File: src/connectiondataholder.cpp (hunk 2 above)
Comment (strseb) [reply src/connectiondataholder.cpp:241]: I'm resetting this in ConnectionDataHolder::reset()  - wouldn't m_checkStatusTimer make it a bit racy? In case e.g. the first request takes longer to complete and the user navigates to the page?

Comment (bakulf) [reply src/connectiondataholder.cpp:241]: m_checkStatusTimer is activated when the info page is shown and it's stopped when the user leaves it. I see the following scenarios:
- the IP check is faster than the navigation and good -> all good!
- the IP check is faster than the navigation but with a failure -> in 3 seconds we try again
- - the IP check is slower than the navigation (at the first shot or the following one) -> when completed, we evaluate the next move.

What do you think?

**Review by bakulf — CHANGES_REQUESTED** [review]

File: src/connectiondataholder.cpp [hunk 4]
```diff
@@ -224,14 +232,27 @@ void ConnectionDataHolder::updateIpAddress() {
...
 
+              QJsonValue country = obj.take("country");
+              if (m_checkStatusTimer.isActive() &&
+                  country.toString().toLower() !=
+                      MozillaVPN::instance()->currentServer()->countryCode()) {
+                // In case the country-we're reported in does not match the
+                // connected server we may retry only once.
+                logger.log() << "Reported ip not in the right country, retry!";
+                TimerSingleShot::create(this, 3000, [this]() {
+                  m_updatingIpAddress = false;
```
Comment (bakulf) [inline src/connectiondataholder.cpp:247]: This line can be removed. If there is another check in progress, we abort the new one.

**Review by bakulf — CHANGES_REQUESTED** [review]
All good! There is only 1 remaining thing: fix the unit tests :)

**Comment by bakulf** [comment]
Thanks!
