### PR TITLE
Android: Disable CaptivePortal and Check FeatureList for ipAllowList

### LINKED ISSUE #860: Cannot activate Mozilla VPN on Android
### Affected versions:
v. 2.1.0 last build;

### Affected Platforms:
- Android 11

### Prerequisites:
- Have a FxA account with active subscription for Mozilla VPN;
- Have a newly installed VPN app;

### Steps to reproduce:
1. Open VPN app;
2. Turn ON the VPN;

### Expected result:
- The VPN is ON.

### Actual result:
- The VPN is not turned ON.

https://user-images.githubusercontent.com/15685960/115019167-7db7b400-9ec1-11eb-86b5-543065d7eef3.mp4

### PR DESCRIPTION
**Pull request by strseb**
2 changes here:
- More logs! And sensitive ones for debug builds. Otherwise i would have not found out what the connection issue was. 
- Also disable CP for android, and double check FeatureList&&Pref like we do with LNA

Closes #860

### CODE REVIEW

File: src/featurelist.cpp [hunk 1]
```diff
@@ -45,7 +45,7 @@ bool FeatureList::protectSelectedAppsSupported() const {
 }
 
 bool FeatureList::captivePortalNotificationSupported() const {
-#if !defined(MVPN_LINUX) || defined(MVPN_MACOS) || defined(MVPN_WINDOWS) || \
+#if defined(MVPN_LINUX) || defined(MVPN_MACOS) || defined(MVPN_WINDOWS) || \
```
Comment (strseb) [inline src/featurelist.cpp:48]: I was not quite shure about this one? - We're supporting CP on linux right? 

This evaluates to true on android, since mvpn_linux is not defined.

**Review by bakulf — APPROVED** [review]
