### PR TITLE
Block all unallowed dns traffic

### LINKED ISSUE #1546: Default DNS leak
#### VPN version:
- 2.5.0 (2.202108091724);

#### Affected Platforms:
- Windows 10;

#### Prerequisites:
- Have one FxA account with subscription for Mozilla VPN;
- Have the VPN installed on your machine;

#### Steps to reproduce:
1. Open VPN app;
2. Go to Settings->Network settings -> Advanced DNS Settings;
3. Enable the “Use default DNS” option.
4. Turn ON the VPN;
5. Access the  https://mullvad.net/en/check/ page

#### Expected result:
- There is no DNS leak.

#### Actual result:
- User default DNS is leaked.
image

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-864)

### PR DESCRIPTION
**Pull request by strseb**
we block all non-tunnel traffic with the killswitch but any dns server reachable through the tunnel may still be used. Lets block all dns traffic unless it's targeted to our dns server from the config. 

closes #1546

### CODE REVIEW

File: src/platforms/windows/daemon/windowsfirewall.cpp [hunk 1]
```diff
@@ -992,3 +993,82 @@ void WindowsFirewall::importAddress(const QHostAddress& addr,
...
+  FWPM_FILTER_CONDITION0 conds[3];
+  conds[0].fieldKey = FWPM_CONDITION_IP_PROTOCOL;
+  conds[0].matchType = FWP_MATCH_EQUAL;
+  conds[0].conditionValue.type = FWP_UINT8;
+  conds[0].conditionValue.uint8 = (IPPROTO_UDP);
+
+  conds[1].fieldKey = FWPM_CONDITION_IP_PROTOCOL;
+  conds[1].matchType = FWP_MATCH_EQUAL;
+  conds[1].conditionValue.type = FWP_UINT8;
+  conds[1].conditionValue.uint16 = (IPPROTO_TCP);
```
Comment (oskirby) [inline src/platforms/windows/daemon/windowsfirewall.cpp:1022]: If the type is `FWP_UINT8` then this should be `conds[1].conditionValue.uint8 = (IPPROTO_TCP)`

**Review by oskirby — CHANGES_REQUESTED** [review]
Looks good, but I would appreciate it if you could address the linter warnings first.

**Review by bakulf — APPROVED** [review]

**Review by oskirby — APPROVED** [review]
